# Generated by Django 4.1.5 on 2023-02-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_rename_first_name_userbase_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbase",
            name="is_subscribed",
            field=models.BooleanField(default=False),
        ),
    ]
