# Generated by Django 4.1.5 on 2023-01-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_name_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='uploads/products/default.jpg', upload_to='uploads/ategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='uploads/products/default.jpg', upload_to='uploads/products/'),
        ),
    ]
