# Generated by Django 4.1.5 on 2023-01-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_category_image_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='uploads/products/default.jpg', upload_to='uploads/products/'),
        ),
    ]
