# Generated by Django 4.1.5 on 2023-02-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_wishlisted',
            field=models.BooleanField(default=False),
        ),
    ]
