# Generated by Django 4.1.5 on 2023-02-08 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="city",
            new_name="country",
        ),
    ]
